{application, brim,
 [{description, "HTML transformation"},
  {vsn, "0.0.1"},
  {modules, [brim,
             brim_html,
             brim_selector_lex,
             brim_selectors,
             trane,
             ziplist,
             ziptree]},
  {registered, []},
  {included_applications, []},
  {applications, [kernel, stdlib]},
  {env, []},
  {mod, {brim_app, []}}]}.
